keks:
  active_id: ENC[AES256_GCM,data:QjZfVNwqGZj+la+lqaWS,iv:NRQHMn2n0pWEf4zjhNX1AXsXbdAP0UFHX0xHY4IW5ts=,tag:jrlhBcYUqCa2236uiAJjGw==,type:str]
  keys:
    kek202603101850: ENC[AES256_GCM,data:Bh7++d0io2MXrwhj9/WAhIQbOdjc7CjDPVZ1LqTjn3TpSxjcxnPXirKqVxA=,iv:ghTJLHiedW9iuPxEbYnnQbxAdIZe27nSo2fLOB7fPy4=,tag:IcJkA8kgdwlE7oAmFBiTIQ==,type:str]
turnstile:
  hostnames:
    softwarepatterns.com:
      jwks_url: ENC[AES256_GCM,data:F6uOBEH86UoNilYg4IBVAchYExB1ybatYSRcV9UpEh6ARqy5KWz01VjFq0LSMQqIONKWFA==,iv:yieuz6mnJZ2hH+z20QbJUPsfEHmcGnMZJP44ov8zZpA=,tag:YYiERnsQGA2rc3pJr2H2ZA==,type:str]
      site_key: ENC[AES256_GCM,data:4z9sQLL1O9rT05blcDIbvL4MuvkkAR3e,iv:6DcrxGBTUkflNuQ343HWb3NSGidAGx5xw2F8OK2uI5A=,tag:UcUw3q9q4MHa1F40lyzk8w==,type:str]
      secret_key: ENC[AES256_GCM,data:6hCCTigLx2MoW0kEYeLvieYSexDFRrFBOrmvFGpg+kcG3Lo=,iv:TuoPZbS8aphjQkLiNE9WODa11S2Ouoi4+iZJgaiCMeU=,tag:74IzNy7i/U7nz3yblSWb2w==,type:str]
sops:
  age:
    - recipient: age1tdyvh0dru9vnyn8em0tp3mye9qma6xqfj4yp6ay65nwyvw94ndasftln49
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3VWU1Y1BQV094VEx3UWgv
        dGJFWFBOeWFaY0dZVWo1QzJ3TGg0NkdyakNRCkI2bzVUWkxza2hUL0kxVVNybUo0
        QUc1cm5SU2dMdFhLVmpybk05SVZPVGsKLS0tIEVyYjBhMWtkNVkrSUlaMWh1M0VH
        NFFGZ0xMa20vUXhDNEVjc3hESnZpemsKeiqWa4rd9Rzhc81/dLQ1ZvsPOvYoVwN5
        MqrFY/skhZrKF51ujoZvn3AMX0UXzmZrkwgemGtR4Ku26WvowYKlww==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age15cwt6yx7pnaxtcffaudtplxzrxfwtz48ydpjst0pr9hwn7ml95rs4c9xxx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCVGl5MSsxNUt5U3dCSGds
        SUgxaEsxUCtjNGgvZ1hOZWI2UzZZNDZOYVJzClJzZkRteUtNckI0SlFCN1dYalgz
        c1FzdGVOeDlsSFBHZ0x5ZDNZNUthQ28KLS0tIFBSSWs2TDB5bDRFQzZiTGhjWlQ1
        QmxMWHd2NnNHQ1UrdnVQZ3djOXBQTzgKSVn4XEjAYOgT0HswFZhtD2YpFYmYfbfy
        7P+hQtekRZx3HS4d3QRqtqc5ICWshZrYInM/Hij1tdqB86+NsSOAJg==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age18aghcthla9kuuqskewwyuk34j9xs346qx2vrwlng20k6dc0yt34szw7p2w
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaZjl1ZjY1RmJ0a2U1eGxk
        QStqNkVEa1pQcVZqRDIwaW9ZdEErOTgvWmxVCnl5YmZjeHJCVFJMOU5zWVNzSmdK
        Zk9tWE43NG53eUVnc0ovN2syRDZSSzgKLS0tIDFEY3lNZXdXMFhOYmo2VTdDYmR6
        aEFXemZ1STVNbmNQdkVpcUNvMnZ4V00KMGv1dHnKFNzdClNKp2iW4vPPBUgFxqTQ
        vu5yLiV2nWOnRu/e6ppQ6IkjdWPXZMel4XsoW1YVriaqGKU5DdBnLA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: '2026-03-10T16:05:19Z'
  mac: ENC[AES256_GCM,data:9bL765ur6nRYdupGMdIqH887x0q1b16JamvrRT/xt+bNya37glFIkBq17cIDRVw04noqqd861NCsaoXynwUMLh1eNcIzEjxeLkmiZysXsvH+LOlI9+o1z37yvJU1opXWqBVIon8zVaNtqEtERA65pzBrC1gVxXg/nWcAjWBw/6I=,iv:6dfuCE2tTbVIClWvLQQqrc0aPS3mFY2JhDn4qqquGDw=,tag:PxxmitgahTy6NtJIPlMdFA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
