name = "newsletters"
main = "src/index.ts"
compatibility_date = "2023-12-18"
tsconfig = "tsconfig.wrangler.json"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "development"

[[d1_databases]]
binding = "NewslettersD1"
database_name = "newsletters"
database_id = "8af56f36-ae7e-4ba6-a8e0-5aa0fe6c16fc"
